### ISSUE TITLE
Optional paramaters shows as required paramaters

### ISSUE THREAD

**Issue by paperclover** [GameMakerDiscord/gml-tools-langserver#9]
functions like instance_destroy() take a variable amount of paramaters (0 - 2), but the lang server marks an error if you do not provide all.

**reproduce: ** type `instance_destroy();` in a gml file.

**Comment by sanbox-irl** [comment]
This is caused by three errors:
1. The linter didn't have any function for knowing "required" vs. "optional" parameters. The skeleton of that has been added, but it will need to be fleshed out. That is a relatively quick job.

2. More fundamentally, the imported manual does not check for optional parameters. This is now being fundamentally rebuilt as the "DocumentationImporter" class, which will handle initial imports of the manual and, in the future, allow users to add arbitrary documentation (as in, document variables, re-do documentation, etc.). That class is being built in branch https://github.com/GameMakerDiscord/gml-tools-langserver/tree/importManual.

3. Parameters are not indexed well if they are optional. This affects script indexing. Essentially, all of the script JSON needs to be reworked in some form or another, so that will be the final pass done.

**Comment by sanbox-irl** [comment]
Completed work in in commit https://github.com/GameMakerDiscord/gml-tools-langserver/commit/37fb2e4e4d31c1bf55437052ed1d303ad0da4e90
